spring.application.name=progetto_finale_michele_macis
spring.datasource.url=jdbc:mysql://localhost:3306/progettoFinaleMicheleMacis
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

supabase.url=https://bgtgdtuqllsyxdoujngo.storage.supabase.co
supabase.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJndGdkdHVxbGxzeXhkb3VqbmdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzkwMTk2MDIsImV4cCI6MjA5NDU5NTYwMn0.c9kJL3OgQAqOM5BLgbYuah5ObUuHRuLx19DP8_BJ6pE
supabase.bucket=/storage/v1/object/bucket_1/
supabase.image=/storage/v1/object/public/bucket_1/

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=da8bdb6d5e038a
spring.mail.password=****91e8
spring.mail.properties.smtp.auth=true
spring.mail.properties.smtp.starttls.enable=true
spring.mail.properties.smtp.starttls.required=true